# Generated by Django 5.1.5 on 2025-02-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
