# Generated by Django 5.1.5 on 2025-02-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
        ("blog", "0006_alter_post_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="auther",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.profile"
            ),
        ),
    ]
